--- understand each column is dimension or measure 

/* =============== step 1 database exploration ============================= */

select * from INFORMATION_SCHEMA.TABLES  -- explore all objects in the database

select * from INFORMATION_SCHEMA.COLUMNS -- explore all columns in the database

/* =============== step 2 Dimensions exploration ============================= */
-- identifying the unique values or categories in each dimenison which help 
-- us to recognizing how data might be grouped or segmented which is useful for later analysis

select * from [dbo].[gold_dim_customer]

select distinct country from [dbo].[gold_dim_customer]

select * from [dbo].[gold_dim_product]

select distinct category from [dbo].[gold_dim_product]

select distinct category,subcategory,product_name from [dbo].[gold_dim_product]
order by 1,2,3

/* =============== step 3 Date exploration ============================= */
-- identify the earliest and latest dates boundaries.understand the scope data and timespan --
-- with the help of this we can analysis year related 

select 
min(order_date) as strtdate, 
max(order_Date) as lastdate,
DATEDIFF(year,min(order_date), max(order_Date)) as yeargap
from 
[dbo].[gold_fact_sales]  -- finding how many years sales are available by checking first  and last order date

select 
min(birth_Date) as oldest,
max(birth_Date) as youngest,
DATEDIFF(year,min(birth_Date),getdate()) as oldest_age,
DATEDIFF(year,max(birth_Date),getdate()) as youngest_age
from [dbo].[gold_dim_customer]  -- find the youngest and oldest customers

/* =============== step 4 Measures exploration ============================= */
-- calculate the key metric of the business (big numbers) 
-- highest levlel of aggregation | lowest level of details 

select sum(sales_amount) as totalsales from [dbo].[gold_fact_sales]

select sum(quantity) as totalsales from [dbo].[gold_fact_sales]

select avg(price) as totalsales from [dbo].[gold_fact_sales]

select count(order_number) as totalorder from [dbo].[gold_fact_sales]
select count(distinct order_number) as totalorder from [dbo].[gold_fact_sales]

select count(product_key) as totalproduct from gold_dim_product
select count(distinct product_key) as totaluniqueproduct from gold_dim_product

select count(customer_key) from [dbo].[gold_dim_customer]
select count(distinct customer_key) from [dbo].[gold_dim_customer]

select customer_key from [dbo].[gold_dim_customer]
where customer_key not in 
(select customer_key from [dbo].[gold_fact_sales])

-- generate a report that shows all key metrics of the businesss 


/* =============== step 5 Magnitude exploration ============================= */
-- compare the measure values against dimension , it help us understand  the importance of different categories

select country, count(customer_key) as total_customer_by_country from [dbo].[gold_dim_customer]
group by country order by total_customer_by_country desc

select gender, count(customer_key) as total_customer_by_gender from [dbo].[gold_dim_customer]
group by gender order by total_customer_by_gender desc

select * from [dbo].[gold_dim_product]
select category, count(product_key) as total_prod_by_cat from [dbo].[gold_dim_product]
group by category order by total_prod_by_cat desc

select category, avg(cost) as avg_cost_by_category from [dbo].[gold_dim_product]
group by category order by avg_cost_by_category desc

select category, sum(cost) as total_revenue_by_category from [dbo].[gold_dim_product]
group by category order by total_revenue_by_category desc

select
pr.category,
sum(sl.sales_amount) as total_revenue
from [dbo].[gold_fact_sales] sl
left join     [dbo].[gold_dim_product] pr
on            sl.product_key=pr.product_key
group by pr.category
order by total_revenue -- total revenue generated by each category

/* =============== step 6 Ranking exploration ============================= */
-- order the value of dimension by measurses in order to identify top/bottom performer